--
-- PostgreSQL database dump
--

-- Dumped from database version 15.2
-- Dumped by pg_dump version 15.2

-- Started on 2023-05-25 16:12:53

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 218 (class 1259 OID 25100)
-- Name: auth_roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_roles (
    id integer NOT NULL,
    value character varying(255) NOT NULL
);


ALTER TABLE public.auth_roles OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 25110)
-- Name: auth_roles_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 25115)
-- Name: cities; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cities (
    id integer NOT NULL,
    name character varying(255) NOT NULL
);


ALTER TABLE public.cities OWNER TO postgres;

--
-- TOC entry 238 (class 1259 OID 25293)
-- Name: comments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.comments (
    id integer NOT NULL,
    group_id integer,
    title character varying(255),
    body character varying(255)
);


ALTER TABLE public.comments OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 25158)
-- Name: cover_letters; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cover_letters (
    id integer NOT NULL,
    user_id integer NOT NULL,
    title character varying(255) NOT NULL,
    body text NOT NULL
);


ALTER TABLE public.cover_letters OWNER TO postgres;

--
-- TOC entry 234 (class 1259 OID 25243)
-- Name: events; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.events (
    id integer NOT NULL,
    user_id integer,
    name character varying(255),
    description character varying(255),
    date_time timestamp without time zone,
    duration interval,
    gro character varying(255),
    url text
);


ALTER TABLE public.events OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 25138)
-- Name: features; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.features (
    id integer NOT NULL,
    name character varying(255) NOT NULL
);


ALTER TABLE public.features OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 25186)
-- Name: features_users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.features_users (
    id integer NOT NULL,
    user_id integer NOT NULL,
    feature_id integer NOT NULL
);


ALTER TABLE public.features_users OWNER TO postgres;

--
-- TOC entry 236 (class 1259 OID 25271)
-- Name: groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.groups (
    id integer NOT NULL,
    name character varying(255),
    status character varying(255)
);


ALTER TABLE public.groups OWNER TO postgres;

--
-- TOC entry 244 (class 1259 OID 25372)
-- Name: interview; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.interview (
    id integer NOT NULL,
    stage_id integer,
    user_id integer,
    resume text,
    date_time timestamp without time zone
);


ALTER TABLE public.interview OWNER TO postgres;

--
-- TOC entry 245 (class 1259 OID 25389)
-- Name: job_experience; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.job_experience (
    id integer NOT NULL,
    user_id integer,
    position_id integer,
    date_start timestamp without time zone,
    date_end timestamp without time zone,
    terms text
);


ALTER TABLE public.job_experience OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 25206)
-- Name: notes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.notes (
    id integer NOT NULL,
    user_id integer,
    title character varying(255),
    body character varying(255),
    date_time timestamp without time zone DEFAULT now()
);


ALTER TABLE public.notes OWNER TO postgres;

--
-- TOC entry 247 (class 1259 OID 25421)
-- Name: notes_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.notes ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.notes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 233 (class 1259 OID 25219)
-- Name: notes_tages; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.notes_tages (
    id integer NOT NULL,
    tag_id integer,
    note_id integer
);


ALTER TABLE public.notes_tages OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 25178)
-- Name: notifications; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.notifications (
    id integer NOT NULL,
    user_id integer NOT NULL,
    title character varying(255) NOT NULL,
    body character varying(255) NOT NULL,
    is_readed boolean DEFAULT false
);


ALTER TABLE public.notifications OWNER TO postgres;

--
-- TOC entry 215 (class 1259 OID 25088)
-- Name: personal_data; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.personal_data (
    id integer NOT NULL,
    email character varying(255) NOT NULL,
    birstday date NOT NULL,
    phone character varying(255) NOT NULL,
    first_name character varying(255),
    mid_name character varying(255),
    last_name character varying(255),
    city_id integer
);


ALTER TABLE public.personal_data OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 25096)
-- Name: personal_data_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.personal_data ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.personal_data_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 25120)
-- Name: positions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.positions (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    description text,
    count integer DEFAULT 1,
    city_id integer
);


ALTER TABLE public.positions OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 25133)
-- Name: positions_features; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.positions_features (
    id integer NOT NULL,
    feature_id integer NOT NULL,
    position_id integer NOT NULL
);


ALTER TABLE public.positions_features OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 25128)
-- Name: positions_skils; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.positions_skils (
    id integer NOT NULL,
    skill_id integer NOT NULL,
    position_id integer NOT NULL
);


ALTER TABLE public.positions_skils OWNER TO postgres;

--
-- TOC entry 242 (class 1259 OID 25347)
-- Name: requests; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.requests (
    id integer NOT NULL,
    group_id integer,
    name character varying(255)
);


ALTER TABLE public.requests OWNER TO postgres;

--
-- TOC entry 243 (class 1259 OID 25357)
-- Name: requests_positions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.requests_positions (
    id integer NOT NULL,
    request_id integer,
    position_id integer
);


ALTER TABLE public.requests_positions OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 25143)
-- Name: skills; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.skills (
    id integer NOT NULL,
    name character varying(255) NOT NULL
);


ALTER TABLE public.skills OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 25148)
-- Name: stages; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.stages (
    id integer NOT NULL,
    name character varying(255) NOT NULL
);


ALTER TABLE public.stages OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 25170)
-- Name: statuses; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.statuses (
    id integer NOT NULL,
    user_id integer NOT NULL,
    name character varying(255) NOT NULL
);


ALTER TABLE public.statuses OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 25153)
-- Name: tages; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tages (
    id integer NOT NULL,
    name character varying(255) NOT NULL
);


ALTER TABLE public.tages OWNER TO postgres;

--
-- TOC entry 240 (class 1259 OID 25320)
-- Name: tests; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tests (
    id integer NOT NULL,
    group_id integer,
    title character varying(255),
    body character varying(255)
);


ALTER TABLE public.tests OWNER TO postgres;

--
-- TOC entry 214 (class 1259 OID 25073)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id integer NOT NULL,
    login character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    registration_date timestamp without time zone DEFAULT now(),
    auth_role_id integer DEFAULT 1
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 239 (class 1259 OID 25305)
-- Name: users_comments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_comments (
    id integer NOT NULL,
    user_id integer,
    comment_id integer
);


ALTER TABLE public.users_comments OWNER TO postgres;

--
-- TOC entry 235 (class 1259 OID 25255)
-- Name: users_events; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_events (
    id integer NOT NULL,
    user_id integer,
    event_id integer
);


ALTER TABLE public.users_events OWNER TO postgres;

--
-- TOC entry 237 (class 1259 OID 25278)
-- Name: users_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_groups (
    id integer NOT NULL,
    user_id integer,
    group_id integer
);


ALTER TABLE public.users_groups OWNER TO postgres;

--
-- TOC entry 216 (class 1259 OID 25095)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 246 (class 1259 OID 25406)
-- Name: users_skills; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_skills (
    id integer NOT NULL,
    user_id integer,
    skill_id integer
);


ALTER TABLE public.users_skills OWNER TO postgres;

--
-- TOC entry 241 (class 1259 OID 25332)
-- Name: users_tests; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_tests (
    id integer NOT NULL,
    user_id integer,
    test_id integer,
    result integer
);


ALTER TABLE public.users_tests OWNER TO postgres;

--
-- TOC entry 3537 (class 0 OID 25100)
-- Dependencies: 218
-- Data for Name: auth_roles; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.auth_roles (id, value) VALUES (1, 'user');
INSERT INTO public.auth_roles (id, value) VALUES (2, 'admin');


--
-- TOC entry 3539 (class 0 OID 25115)
-- Dependencies: 220
-- Data for Name: cities; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3557 (class 0 OID 25293)
-- Dependencies: 238
-- Data for Name: comments; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3547 (class 0 OID 25158)
-- Dependencies: 228
-- Data for Name: cover_letters; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3553 (class 0 OID 25243)
-- Dependencies: 234
-- Data for Name: events; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3543 (class 0 OID 25138)
-- Dependencies: 224
-- Data for Name: features; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3550 (class 0 OID 25186)
-- Dependencies: 231
-- Data for Name: features_users; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3555 (class 0 OID 25271)
-- Dependencies: 236
-- Data for Name: groups; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3563 (class 0 OID 25372)
-- Dependencies: 244
-- Data for Name: interview; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3564 (class 0 OID 25389)
-- Dependencies: 245
-- Data for Name: job_experience; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3551 (class 0 OID 25206)
-- Dependencies: 232
-- Data for Name: notes; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.notes (id, user_id, title, body, date_time) OVERRIDING SYSTEM VALUE VALUES (1, 1, 'Test 1', 'dfsfwfsfsefwfwfwcvwcvwevc', '2023-05-25 15:10:17.031013');


--
-- TOC entry 3552 (class 0 OID 25219)
-- Dependencies: 233
-- Data for Name: notes_tages; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3549 (class 0 OID 25178)
-- Dependencies: 230
-- Data for Name: notifications; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3534 (class 0 OID 25088)
-- Dependencies: 215
-- Data for Name: personal_data; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.personal_data (id, email, birstday, phone, first_name, mid_name, last_name, city_id) VALUES (1, 'masha@gmail.com', '2000-01-01', '+79998887766', 'Мария', 'Ивановна', 'Иванова', NULL);


--
-- TOC entry 3540 (class 0 OID 25120)
-- Dependencies: 221
-- Data for Name: positions; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3542 (class 0 OID 25133)
-- Dependencies: 223
-- Data for Name: positions_features; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3541 (class 0 OID 25128)
-- Dependencies: 222
-- Data for Name: positions_skils; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3561 (class 0 OID 25347)
-- Dependencies: 242
-- Data for Name: requests; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3562 (class 0 OID 25357)
-- Dependencies: 243
-- Data for Name: requests_positions; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3544 (class 0 OID 25143)
-- Dependencies: 225
-- Data for Name: skills; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3545 (class 0 OID 25148)
-- Dependencies: 226
-- Data for Name: stages; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3548 (class 0 OID 25170)
-- Dependencies: 229
-- Data for Name: statuses; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3546 (class 0 OID 25153)
-- Dependencies: 227
-- Data for Name: tages; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3559 (class 0 OID 25320)
-- Dependencies: 240
-- Data for Name: tests; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3533 (class 0 OID 25073)
-- Dependencies: 214
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.users (id, login, password, registration_date, auth_role_id) VALUES (1, 'maria', '12345', '2023-05-22 14:05:12.056031', 1);
INSERT INTO public.users (id, login, password, registration_date, auth_role_id) VALUES (11, 'admin', '$2a$07$hET7sI2ElSNaIC3l4JnwHu35mUfENBAINbf5iP4wIkWa/2HN.GXRC', '2023-05-23 16:37:13.411902', 2);
INSERT INTO public.users (id, login, password, registration_date, auth_role_id) VALUES (9, 'petro44', '$2a$07$N9bkG1QAA758PzJJDbS.HO5kRXZW4b5wB.oxiA3T1G86MtDYn3Nje', '2023-05-23 15:14:06.649664', 1);


--
-- TOC entry 3558 (class 0 OID 25305)
-- Dependencies: 239
-- Data for Name: users_comments; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3554 (class 0 OID 25255)
-- Dependencies: 235
-- Data for Name: users_events; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3556 (class 0 OID 25278)
-- Dependencies: 237
-- Data for Name: users_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3565 (class 0 OID 25406)
-- Dependencies: 246
-- Data for Name: users_skills; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3560 (class 0 OID 25332)
-- Dependencies: 241
-- Data for Name: users_tests; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3572 (class 0 OID 0)
-- Dependencies: 219
-- Name: auth_roles_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_roles_id_seq', 2, true);


--
-- TOC entry 3573 (class 0 OID 0)
-- Dependencies: 247
-- Name: notes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.notes_id_seq', 1, true);


--
-- TOC entry 3574 (class 0 OID 0)
-- Dependencies: 217
-- Name: personal_data_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.personal_data_id_seq', 1, true);


--
-- TOC entry 3575 (class 0 OID 0)
-- Dependencies: 216
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 11, true);


--
-- TOC entry 3304 (class 2606 OID 25119)
-- Name: cities cities_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cities
    ADD CONSTRAINT cities_pkey PRIMARY KEY (id);


--
-- TOC entry 3340 (class 2606 OID 25299)
-- Name: comments comments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT comments_pkey PRIMARY KEY (id);


--
-- TOC entry 3320 (class 2606 OID 25164)
-- Name: cover_letters cover_letters_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cover_letters
    ADD CONSTRAINT cover_letters_pkey PRIMARY KEY (id);


--
-- TOC entry 3332 (class 2606 OID 25249)
-- Name: events events_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.events
    ADD CONSTRAINT events_pkey PRIMARY KEY (id);


--
-- TOC entry 3326 (class 2606 OID 25190)
-- Name: features_users features_users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.features_users
    ADD CONSTRAINT features_users_pkey PRIMARY KEY (id);


--
-- TOC entry 3300 (class 2606 OID 25094)
-- Name: personal_data firstkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.personal_data
    ADD CONSTRAINT firstkey PRIMARY KEY (id);


--
-- TOC entry 3302 (class 2606 OID 25104)
-- Name: auth_roles firstkey_auth_roles; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_roles
    ADD CONSTRAINT firstkey_auth_roles PRIMARY KEY (id);


--
-- TOC entry 3336 (class 2606 OID 25277)
-- Name: groups groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.groups
    ADD CONSTRAINT groups_pkey PRIMARY KEY (id);


--
-- TOC entry 3352 (class 2606 OID 25378)
-- Name: interview interview_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.interview
    ADD CONSTRAINT interview_pkey PRIMARY KEY (id);


--
-- TOC entry 3354 (class 2606 OID 25395)
-- Name: job_experience job_experience_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.job_experience
    ADD CONSTRAINT job_experience_pkey PRIMARY KEY (id);


--
-- TOC entry 3328 (class 2606 OID 25213)
-- Name: notes notes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notes
    ADD CONSTRAINT notes_pkey PRIMARY KEY (id);


--
-- TOC entry 3330 (class 2606 OID 25223)
-- Name: notes_tages notes_tages_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notes_tages
    ADD CONSTRAINT notes_tages_pkey PRIMARY KEY (id);


--
-- TOC entry 3324 (class 2606 OID 25185)
-- Name: notifications notification_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notification_pkey PRIMARY KEY (id);


--
-- TOC entry 3306 (class 2606 OID 25127)
-- Name: positions positions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.positions
    ADD CONSTRAINT positions_pkey PRIMARY KEY (id);


--
-- TOC entry 3308 (class 2606 OID 25132)
-- Name: positions_skils positions_skils_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.positions_skils
    ADD CONSTRAINT positions_skils_pkey PRIMARY KEY (id);


--
-- TOC entry 3310 (class 2606 OID 25137)
-- Name: positions_features positions_terms_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.positions_features
    ADD CONSTRAINT positions_terms_pkey PRIMARY KEY (id);


--
-- TOC entry 3348 (class 2606 OID 25351)
-- Name: requests requestes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.requests
    ADD CONSTRAINT requestes_pkey PRIMARY KEY (id);


--
-- TOC entry 3350 (class 2606 OID 25361)
-- Name: requests_positions requests_positions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.requests_positions
    ADD CONSTRAINT requests_positions_pkey PRIMARY KEY (id);


--
-- TOC entry 3314 (class 2606 OID 25147)
-- Name: skills skills_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.skills
    ADD CONSTRAINT skills_pkey PRIMARY KEY (id);


--
-- TOC entry 3316 (class 2606 OID 25152)
-- Name: stages stages_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.stages
    ADD CONSTRAINT stages_pkey PRIMARY KEY (id);


--
-- TOC entry 3322 (class 2606 OID 25177)
-- Name: statuses statuses_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.statuses
    ADD CONSTRAINT statuses_pkey PRIMARY KEY (id);


--
-- TOC entry 3318 (class 2606 OID 25157)
-- Name: tages tages_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tages
    ADD CONSTRAINT tages_pkey PRIMARY KEY (id);


--
-- TOC entry 3312 (class 2606 OID 25142)
-- Name: features terms_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.features
    ADD CONSTRAINT terms_pkey PRIMARY KEY (id);


--
-- TOC entry 3344 (class 2606 OID 25326)
-- Name: tests tests_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tests
    ADD CONSTRAINT tests_pkey PRIMARY KEY (id);


--
-- TOC entry 3342 (class 2606 OID 25309)
-- Name: users_comments users_comments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_comments
    ADD CONSTRAINT users_comments_pkey PRIMARY KEY (id);


--
-- TOC entry 3334 (class 2606 OID 25259)
-- Name: users_events users_events_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_events
    ADD CONSTRAINT users_events_pkey PRIMARY KEY (id);


--
-- TOC entry 3338 (class 2606 OID 25282)
-- Name: users_groups users_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_groups
    ADD CONSTRAINT users_groups_pkey PRIMARY KEY (id);


--
-- TOC entry 3298 (class 2606 OID 25077)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 3356 (class 2606 OID 25410)
-- Name: users_skills users_skills_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_skills
    ADD CONSTRAINT users_skills_pkey PRIMARY KEY (id);


--
-- TOC entry 3346 (class 2606 OID 25336)
-- Name: users_tests users_tests_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_tests
    ADD CONSTRAINT users_tests_pkey PRIMARY KEY (id);


--
-- TOC entry 3376 (class 2606 OID 25300)
-- Name: comments comments_group_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT comments_group_id_fkey FOREIGN KEY (group_id) REFERENCES public.groups(id);


--
-- TOC entry 3363 (class 2606 OID 25467)
-- Name: cover_letters cover_letters_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cover_letters
    ADD CONSTRAINT cover_letters_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) NOT VALID;


--
-- TOC entry 3371 (class 2606 OID 25250)
-- Name: events events_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.events
    ADD CONSTRAINT events_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 3366 (class 2606 OID 25442)
-- Name: features_users features_users_feature_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.features_users
    ADD CONSTRAINT features_users_feature_id_fkey FOREIGN KEY (feature_id) REFERENCES public.features(id) NOT VALID;


--
-- TOC entry 3367 (class 2606 OID 25437)
-- Name: features_users features_users_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.features_users
    ADD CONSTRAINT features_users_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) NOT VALID;


--
-- TOC entry 3385 (class 2606 OID 25379)
-- Name: interview interview_stage_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.interview
    ADD CONSTRAINT interview_stage_id_fkey FOREIGN KEY (stage_id) REFERENCES public.stages(id);


--
-- TOC entry 3386 (class 2606 OID 25384)
-- Name: interview interview_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.interview
    ADD CONSTRAINT interview_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 3387 (class 2606 OID 25401)
-- Name: job_experience job_experience_position_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.job_experience
    ADD CONSTRAINT job_experience_position_id_fkey FOREIGN KEY (position_id) REFERENCES public.positions(id);


--
-- TOC entry 3388 (class 2606 OID 25396)
-- Name: job_experience job_experience_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.job_experience
    ADD CONSTRAINT job_experience_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 3369 (class 2606 OID 25229)
-- Name: notes_tages notes_tages_note_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notes_tages
    ADD CONSTRAINT notes_tages_note_id_fkey FOREIGN KEY (note_id) REFERENCES public.notes(id);


--
-- TOC entry 3370 (class 2606 OID 25224)
-- Name: notes_tages notes_tages_tag_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notes_tages
    ADD CONSTRAINT notes_tages_tag_id_fkey FOREIGN KEY (tag_id) REFERENCES public.tages(id);


--
-- TOC entry 3368 (class 2606 OID 25214)
-- Name: notes notes_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notes
    ADD CONSTRAINT notes_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 3365 (class 2606 OID 25422)
-- Name: notifications notification_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notification_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) NOT VALID;


--
-- TOC entry 3357 (class 2606 OID 25427)
-- Name: personal_data personal_data_city_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.personal_data
    ADD CONSTRAINT personal_data_city_id_fkey FOREIGN KEY (city_id) REFERENCES public.cities(id) NOT VALID;


--
-- TOC entry 3358 (class 2606 OID 25432)
-- Name: positions positions_city_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.positions
    ADD CONSTRAINT positions_city_id_fkey FOREIGN KEY (city_id) REFERENCES public.cities(id) NOT VALID;


--
-- TOC entry 3361 (class 2606 OID 25447)
-- Name: positions_features positions_features_feature_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.positions_features
    ADD CONSTRAINT positions_features_feature_id_fkey FOREIGN KEY (feature_id) REFERENCES public.features(id) NOT VALID;


--
-- TOC entry 3362 (class 2606 OID 25452)
-- Name: positions_features positions_features_position_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.positions_features
    ADD CONSTRAINT positions_features_position_id_fkey FOREIGN KEY (position_id) REFERENCES public.positions(id) NOT VALID;


--
-- TOC entry 3359 (class 2606 OID 25462)
-- Name: positions_skils positions_skils_position_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.positions_skils
    ADD CONSTRAINT positions_skils_position_id_fkey FOREIGN KEY (position_id) REFERENCES public.positions(id) NOT VALID;


--
-- TOC entry 3360 (class 2606 OID 25457)
-- Name: positions_skils positions_skils_skill_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.positions_skils
    ADD CONSTRAINT positions_skils_skill_id_fkey FOREIGN KEY (skill_id) REFERENCES public.skills(id) NOT VALID;


--
-- TOC entry 3382 (class 2606 OID 25352)
-- Name: requests requestes_group_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.requests
    ADD CONSTRAINT requestes_group_id_fkey FOREIGN KEY (group_id) REFERENCES public.groups(id);


--
-- TOC entry 3383 (class 2606 OID 25367)
-- Name: requests_positions requests_positions_position_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.requests_positions
    ADD CONSTRAINT requests_positions_position_id_fkey FOREIGN KEY (position_id) REFERENCES public.positions(id);


--
-- TOC entry 3384 (class 2606 OID 25362)
-- Name: requests_positions requests_positions_request_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.requests_positions
    ADD CONSTRAINT requests_positions_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.requests(id);


--
-- TOC entry 3364 (class 2606 OID 25472)
-- Name: statuses statuses_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.statuses
    ADD CONSTRAINT statuses_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) NOT VALID;


--
-- TOC entry 3379 (class 2606 OID 25327)
-- Name: tests tests_group_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tests
    ADD CONSTRAINT tests_group_id_fkey FOREIGN KEY (group_id) REFERENCES public.groups(id);


--
-- TOC entry 3377 (class 2606 OID 25315)
-- Name: users_comments users_comments_comment_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_comments
    ADD CONSTRAINT users_comments_comment_id_fkey FOREIGN KEY (comment_id) REFERENCES public.comments(id);


--
-- TOC entry 3378 (class 2606 OID 25310)
-- Name: users_comments users_comments_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_comments
    ADD CONSTRAINT users_comments_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 3372 (class 2606 OID 25265)
-- Name: users_events users_events_event_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_events
    ADD CONSTRAINT users_events_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id);


--
-- TOC entry 3373 (class 2606 OID 25260)
-- Name: users_events users_events_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_events
    ADD CONSTRAINT users_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 3374 (class 2606 OID 25288)
-- Name: users_groups users_groups_group_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_groups
    ADD CONSTRAINT users_groups_group_id_fkey FOREIGN KEY (group_id) REFERENCES public.groups(id);


--
-- TOC entry 3375 (class 2606 OID 25283)
-- Name: users_groups users_groups_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_groups
    ADD CONSTRAINT users_groups_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 3389 (class 2606 OID 25416)
-- Name: users_skills users_skills_skill_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_skills
    ADD CONSTRAINT users_skills_skill_id_fkey FOREIGN KEY (skill_id) REFERENCES public.skills(id);


--
-- TOC entry 3390 (class 2606 OID 25411)
-- Name: users_skills users_skills_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_skills
    ADD CONSTRAINT users_skills_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 3380 (class 2606 OID 25342)
-- Name: users_tests users_tests_test_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_tests
    ADD CONSTRAINT users_tests_test_id_fkey FOREIGN KEY (test_id) REFERENCES public.tests(id);


--
-- TOC entry 3381 (class 2606 OID 25337)
-- Name: users_tests users_tests_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_tests
    ADD CONSTRAINT users_tests_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


-- Completed on 2023-05-25 16:12:53

--
-- PostgreSQL database dump complete
--

