--
-- PostgreSQL database dump
--

-- Dumped from database version 15.2
-- Dumped by pg_dump version 15.2

-- Started on 2023-05-23 16:08:38

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 3344 (class 1262 OID 25072)
-- Name: recruitment; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE recruitment WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'Russian_Russia.1251';


ALTER DATABASE recruitment OWNER TO postgres;

\connect recruitment

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 218 (class 1259 OID 25100)
-- Name: auth_roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_roles (
    id integer NOT NULL,
    value character varying(255) NOT NULL
);


ALTER TABLE public.auth_roles OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 25110)
-- Name: auth_roles_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 215 (class 1259 OID 25088)
-- Name: personal_data; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.personal_data (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    surname character varying(255) NOT NULL,
    e_mail character varying(255) NOT NULL,
    city character varying(255) NOT NULL,
    birstday date NOT NULL,
    status character varying(255) NOT NULL,
    phone character varying(255) NOT NULL
);


ALTER TABLE public.personal_data OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 25096)
-- Name: personal_data_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.personal_data ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.personal_data_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 214 (class 1259 OID 25073)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id integer NOT NULL,
    login character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    registration_date timestamp without time zone DEFAULT now(),
    auth_role_id integer DEFAULT 1
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 216 (class 1259 OID 25095)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3337 (class 0 OID 25100)
-- Dependencies: 218
-- Data for Name: auth_roles; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.auth_roles (id, value) VALUES (1, 'user');
INSERT INTO public.auth_roles (id, value) VALUES (2, 'admin');


--
-- TOC entry 3334 (class 0 OID 25088)
-- Dependencies: 215
-- Data for Name: personal_data; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.personal_data (id, name, surname, e_mail, city, birstday, status, phone) VALUES (1, 'Мария', 'Машина', 'masha@gmail.com', 'Москва', '2000-01-01', 'Ищу работу', '+79998887766');


--
-- TOC entry 3333 (class 0 OID 25073)
-- Dependencies: 214
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.users (id, login, password, registration_date, auth_role_id) VALUES (1, 'maria', '12345', '2023-05-22 14:05:12.056031', 1);
INSERT INTO public.users (id, login, password, registration_date, auth_role_id) VALUES (2, 'Sasha', '12345', '2023-05-23 14:24:01.007482', 1);
INSERT INTO public.users (id, login, password, registration_date, auth_role_id) VALUES (3, 'Dasha', '12345', '2023-05-23 14:30:03.944746', 1);
INSERT INTO public.users (id, login, password, registration_date, auth_role_id) VALUES (5, 'mira', '54321', '2023-05-23 14:44:31.157965', 1);
INSERT INTO public.users (id, login, password, registration_date, auth_role_id) VALUES (6, 'miram', '54321', '2023-05-23 14:45:48.812687', 1);
INSERT INTO public.users (id, login, password, registration_date, auth_role_id) VALUES (7, 'petr', '54321', '2023-05-23 15:01:58.41976', 1);
INSERT INTO public.users (id, login, password, registration_date, auth_role_id) VALUES (8, 'petrov22', '54321', '2023-05-23 15:02:45.597583', 1);
INSERT INTO public.users (id, login, password, registration_date, auth_role_id) VALUES (9, 'petro44', '$2a$07$N9bkG1QAA758PzJJDbS.HO5kRXZW4b5wB.oxiA3T1G86MtDYn3Nje', '2023-05-23 15:14:06.649664', 1);
INSERT INTO public.users (id, login, password, registration_date, auth_role_id) VALUES (10, '', '$2a$07$GpRqccXc3IYSjd.cuJ63jOrVVmoXEhw3vx/YHyAL1H5iKOhLS2NUK', '2023-05-23 15:19:51.438612', 1);


--
-- TOC entry 3345 (class 0 OID 0)
-- Dependencies: 219
-- Name: auth_roles_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_roles_id_seq', 2, true);


--
-- TOC entry 3346 (class 0 OID 0)
-- Dependencies: 217
-- Name: personal_data_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.personal_data_id_seq', 1, true);


--
-- TOC entry 3347 (class 0 OID 0)
-- Dependencies: 216
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 10, true);


--
-- TOC entry 3188 (class 2606 OID 25094)
-- Name: personal_data firstkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.personal_data
    ADD CONSTRAINT firstkey PRIMARY KEY (id);


--
-- TOC entry 3190 (class 2606 OID 25104)
-- Name: auth_roles firstkey_auth_roles; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_roles
    ADD CONSTRAINT firstkey_auth_roles PRIMARY KEY (id);


--
-- TOC entry 3186 (class 2606 OID 25077)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


-- Completed on 2023-05-23 16:08:38

--
-- PostgreSQL database dump complete
--

